/**
 * @file types/payment.type.ts
 *
 * @summary Defines types related to payments, including status, methods, and payloads.
 */

import { Timestamp } from "firebase-admin/firestore";
import { APP } from "@/types/app.type";

/**
 * Possible statuses for a payment.
 */
export type PaymentStatus =
  | "PENDING" // Awaiting payment
  | "PAID" // Paid
  | "CANCELLED" // Cancelled
  | "REFUNDED" // Refunded
  | "BANK_PROCESSING" // Sent to bank
  | "FAILED" // Failed
  | "AWAITING_CHECKOUT_RISK_ANALYSIS_REQUEST"; // Under risk analysis

/**
 * Payment methods accepted.
 */
export type PaymentMethod = "CREDIT_CARD" | "PIX" | "BOLETO";

/**
 * Represents a payment record.
 */
export interface Payment {
  /** Unique UUID for this payment */
  id: string;

  /** UUID of the user who made the payment */
  userId: string;

  /** Customer's full name */
  customerName: string;

  /** Customer's CPF */
  customerCpf: string;

  /** Payment ID generated by the gateway (for reference and deduplication) */
  gatewayPaymentId: string;

  /** Gateway event ID (useful for webhook auditing) */
  gatewayEventId?: string;

  /** Payment amount in BRL */
  amount: number;

  /** Payment method used */
  method: PaymentMethod;

  /** Current payment status */
  status: PaymentStatus;

  /** Date/time when payment was confirmed by the gateway (ISO 8601) */
  paymentDate: Timestamp | string;

  /** Timestamp when the record was created */
  createdAt?: Timestamp;

  /** Description of the payment (e.g., "Physical Student Card") */
  description?: string;

  /** Raw payload from the gateway (useful for auditing/debugging) */
  metadata?: Record<string, unknown>;

  /** Application this payment belongs to */
  app: APP;
}

/** Payload used to create a new payment (includes ID) */
export type PaymentCreatePayload = Payment;

/** Aggregated statistics for payments */
export interface PaymentsStats {
  /** Total number of payments */
  count: number;

  /** Total sum of all payment amounts */
  totalAmount: number;
}
